import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import CssBaseline from '@mui/material/CssBaseline';
import TextField from '@mui/material/TextField';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Link from '@mui/material/Link';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import {useRouter} from 'next/router'
import { useAppDispatch, useAppSelector, setInfo, addTag, increaseTagCount } from "@/components/store";
import {Badge, Chip, Divider, IconButton, InputBase, ListItemAvatar, Paper} from "@mui/material";
import {Menu, Search, Directions, Favorite, Face} from "@mui/icons-material";
import MiniDrawer from "@/components/drawer";
import {useState} from "react";
import MainModal from "@/components/modal/mainModal";
import * as React from "react";
import FriendSearchModal from "@/components/modal/friendSearchModal";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import ListItemButton from "@mui/material/ListItemButton";
import {Map, MapMarker} from "react-kakao-maps-sdk";

const inter = Inter({ subsets: ['latin'] })

interface Info {
    id: string,
    password: string,
    nickname: string,
    tag: []
}

export default function Home() {
    const router = useRouter()
    const dispatch = useAppDispatch()
    const info: any | Info = useAppSelector(state => state.userInfo)

    const handleClick = (...rest: any[]) => {
        const index = rest[0]
        dispatch(increaseTagCount(index))
    };

    const handleDelete = (...rest: any[]) => {
        console.info('You clicked the delete icon.');
    };
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <MiniDrawer/>
                <Box sx={{
                    display: 'flex',
                    flexWrap: 'wrap',
                    flexDirection: 'column',
                    justifyContent: 'flex-end',
                    alignItems: 'center',
                    paddingTop: '3rem',
                    paddingLeft: '3rem'
                }}>

                    <Map // 지도를 표시할 Container
                        center={{
                            // 지도의 중심좌표
                            lat: 33.450701,
                            lng: 126.570667,
                        }}

                        style={{
                            // 지도의 크기
                            width: "100vh",
                            height: "100vh",
                            zIndex: '1'
                        }}
                        level={3} // 지도의 확대 레벨
                    />
                    <Paper
                        component="form"
                        sx={{ position: 'absolute', top: '5rem', width: 4/5, zIndex: '2' }}
                    >
                        <Box sx={{
                            display: 'flex',
                            flexDirection: 'row',
                            justifyContent: 'space-between'
                        }}>

                            <InputBase
                                sx={{ ml: 1, width: 4/5 }}
                                placeholder="장소를 찾아보세요"
                                inputProps={{
                                    'aria-label': 'search kakao maps',
                                    maxLength: 20
                                }}
                            />
                            <IconButton type="button" sx={{ p: '10px' }} aria-label="search">
                                <Search />
                            </IconButton>
                        </Box>

                    </Paper>
                </Box>
            </main>
        </>
    )
}
