import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import CssBaseline from '@mui/material/CssBaseline';
import TextField from '@mui/material/TextField';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Link from '@mui/material/Link';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import {useRouter} from 'next/router'
import { useAppDispatch, useAppSelector, setInfo, addTag, increaseTagCount } from "@/components/store";
import {Badge, Chip, Divider, IconButton, InputBase, Paper} from "@mui/material";
import {Menu, Search, Directions, Favorite, Face} from "@mui/icons-material";
import MiniDrawer from "@/components/drawer";
import {useRef, useState} from "react";
import MainModal from "@/components/modal/mainModal";
import * as React from "react";

const inter = Inter({ subsets: ['latin'] })

interface Info {
    id: string,
    password: string,
    nickname: string,
    tag: []
}

export default function Home() {
    const router = useRouter()
    const dispatch = useAppDispatch()
    const info: any | Info = useAppSelector(state => state.userInfo)

    const [inputs, setInputs] = useState({
        name: '',
        icon: '',
        count: 1
    })
    const {name, icon, count} = inputs;

    const [chips, setChips] = useState([
        {
            id: 1,
            name: 'a',
            icon: '',
            count: 1
        },
        {
            id: 2,
            name: 'b',
            icon: '',
            count: 1
        },
        {
            id: 3,
            name: 'c',
            icon: '',
            count: 1
        },
    ]);
    const nextId = useRef(4);

    // @ts-ignore
    const onChange = (e) => {
        const { name, value } = e.target;
        setInputs({
            ...inputs,
            [name]: value,
        });
    };

    const onCreate = () => {
        const chip = {
            id: nextId.current,
            name,
            icon,
            count
        };

        setChips([...chips, chip]);

        setInputs({
            name: "",
            icon: "",
            count: 1
        });
        nextId.current += 1;
    };


    const onIncrease = (index: number) => {
        let copyArray = [...chips]
        let copyCount = chips[index].count
        copyArray[index] = {...copyArray[index], count: copyCount+1 }
        setChips(copyArray)
    }

    // @ts-ignore
    const onRemove = id => {
        // user.id 가 파라미터로 일치하지 않는 원소만 추출해서 새로운 배열을 만듬
        // = user.id 가 id 인 것을 제거함
        setChips(chips.filter(chip => chip.id !== id));
    };


    const handleClick = (...rest: any[]) => {
        const index = rest[0]
        onIncrease(index)
        console.info('clicked', index, chips[index].count)
        // dispatch(increaseTagCount(index))
    };

    const handleDelete = (...rest: any[]) => {
        const id = rest[0]
        console.info('You clicked the delete icon.');
        onRemove(id)
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <MiniDrawer/>
                <Box sx={{
                    display: 'flex',
                    flexWrap: 'wrap',
                    flexDirection: 'column',
                    justifyContent: 'flex-end',
                    alignItems: 'center',
                    paddingTop: '4rem',
                    paddingLeft: '2rem'
                }}>
                    <img src={"/logo.png"} style={{
                        width: 120,
                        height: 120,
                        margin: 20
                    }}/>
                    <Typography variant="h6" gutterBottom>
                        소소식탁
                    </Typography>
                    <MainModal/>
                    <Box sx={{
                        display: 'flex',
                        flexWrap: 'wrap',
                        flexDirection: 'row',
                        justifyContent: 'center',
                        alignItems: 'center',
                        margin: '10px'
                    }}>
                        {/*

                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip
                                icon={<Face />}
                                label="팥붕"
                                onClick={onIncrease}
                                onDelete={handleDelete}
                            />
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip
                                label="데이먼스 이어"
                                onClick={onIncrease}
                                onDelete={handleDelete}
                            />
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip
                                label="매운거"
                                onClick={handleClick}
                                onDelete={handleDelete}
                            />
                        </Badge>



                        {
                            info.tag.map((element: Info | any, index: number) => (
                                <Badge
                                    badgeContent={count[index]}
                                    color="primary"
                                    key={index}
                                    style={{
                                        margin: 10
                                    }}>
                                    <Chip
                                        label={element.value + index}
                                        onClick={() => handleClick(index)}
                                        onDelete={() => handleDelete(index)}
                                    />
                                </Badge>
                            ))
                        }
                    */}

                        {
                            chips.map((chip, index) => (
                                <Badge
                                    badgeContent={chip.count}
                                    color="primary"
                                    key={chip.id}
                                    style={{
                                        margin: 10
                                    }}>
                                    <Chip
                                        label={chip.name}
                                        onClick={() => handleClick(index)}
                                        onDelete={() => handleDelete(chip.id)}
                                    />
                                </Badge>

                            ))
                        }


                    </Box>
                </Box>
            </main>
        </>
    )
}
