import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import CssBaseline from '@mui/material/CssBaseline';
import TextField from '@mui/material/TextField';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Link from '@mui/material/Link';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import {useRouter} from 'next/router'
import { useAppDispatch, useAppSelector, setInfo } from "@/components/store";
import {Badge, Chip, Divider, IconButton, InputBase, Paper} from "@mui/material";
import {Menu, Search, Directions} from "@mui/icons-material";
import MiniDrawer from "@/components/drawer";
function Copyright(props: any) {

    return (
        <Typography variant="body2" color="text.secondary" align="center" {...props}>
            {'Copyright © '}
            <Link color="inherit" href="https://mui.com/">
                Your Website
            </Link>{' '}
            {new Date().getFullYear()}
            {'.'}
        </Typography>
    );
}

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <MiniDrawer/>
                <Box sx={{
                    display: 'flex',
                    flexWrap: 'wrap',
                    flexDirection: 'column',
                    justifyContent: 'flex-end',
                    alignItems: 'center',
                    paddingTop: '2rem',
                    paddingLeft: '2rem'
                }}>
                    <img src={"/logo.png"} style={{
                        width: 180,
                        height: 180,
                        margin: 20
                    }}/>

                    <Box sx={{
                        display: 'flex',
                        flexWrap: 'wrap',
                        flexDirection: 'row',
                        justifyContent: 'center',
                        alignItems: 'center',
                        margin: '10px'
                    }}>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip label="Clickable"/>
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip label="Clickable"/>
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip label="Clickable"/>
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip label="Clickable"/>
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip label="Clickable"/>
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip label="Clickable"/>
                        </Badge>
                        <Badge badgeContent={4} color="primary" style={{
                            margin: 10
                        }}>
                            <Chip label="Clickable"/>
                        </Badge>
                    </Box>
                    <Paper
                        component="form"
                        sx={{ p: '2px 4px', display: 'flex', alignItems: 'center', width: 4/5 }}
                    >
                        <InputBase
                            sx={{ ml: 1, flex: 1 }}
                            placeholder="add"
                            inputProps={{ 'aria-label': 'add' }}
                        />
                        <IconButton type="button" sx={{ p: '10px' }} aria-label="search">
                            <Search />
                        </IconButton>
                    </Paper>
                </Box>
            </main>
        </>
    )
}
